### ISSUE TITLE
Allow the ability to add 3th party tasks

### ISSUE THREAD

**Issue by shayki5** [damienaicheh/azure-devops-snippets-generator#2]
Hi!
Very cool extension!
I see in your code that you clone the out-of-the-box tasks and generate the snippets. 
But, there are many tasks in the marketplace, can you allow the ability to add them also?
Maybe a folder in your repo with other tasks that you will read?

Best regards,
Shayki

**Comment by damienaicheh** [comment]
Hi,
I had this idea in mind but I wanted to keep only the official tasks in one extension for consistency.
I don't know if it will be useful for some one to have all snippets for all existing tasks that can be up to date, not maintained or deprecated because of their owners . The Microsoft Tasks are all maintains and up to date that's why I only used this repo for the moment.

**Comment by shayki5** [comment]
@damienaicheh Ok 👍 
Thank you!

**Comment by vercellone** [comment]
If this code were reworked to use an [Azure Pipelines](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines) schema file as input instead of the Microsoft tasks repo, it should be trivial to use a custom schema file downloaded from https://dev.azure.com/YOUR-ORG-HERE/_apis/distributedtask/yamlschema to facilitate this use case.
