### ISSUE TITLE
Add snippets for 'Azure Pipelines' Language Mode

### ISSUE THREAD

**Issue by jinyeow** [damienaicheh/azure-devops-snippets-generator#6]
FEATURE REQUEST

I am using the Azure Pipelines VScode extension which gives the language mode "Azure Pipelines":
![image](https://user-images.githubusercontent.com/6980787/166174297-3b428be8-d1e9-4567-a760-9fa935e3ae52.png)
![image](https://user-images.githubusercontent.com/6980787/166174310-595a88cd-a66c-46f7-b173-cbf388d54e67.png)

If possible, it would be really helpful if this snippets generator plugin also worked on that language mode.

**Comment by damienaicheh** [comment]
Based on my comprehension, you have this option because you have another plugin or something else that define this language. It's not on the VS Code language list:
https://code.visualstudio.com/docs/languages/identifiers

**Comment by doggy8088** [comment]
@damienaicheh I think many of the Azure Pipelines YAML developers could very possible installed [Azure Pipelines](https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines) extension. That's why @jinyeow shows this language mode.

I think this feature request is quite reasonable. Would you please reconsider add this?

**Comment by damienaicheh** [comment]
Like I said in the previous post I didn't find the way to do this in the VS Code documentation. If you see how, feel free to do a PR.
